###############################################
# Yahoo service
###############################################
apiVersion: v1
kind: Service
metadata:
  name: yahoo
  labels:
    app: yahoo
    service: yahoo
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: yahoo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: yahoo-api
  labels:
    account: yahoo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yahoo-v1
  labels:
    app: yahoo
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yahoo
      version: v1
  template:
    metadata:
      labels:
        app: yahoo
        version: v1
    spec:
      serviceAccountName: yahoo-api
      containers:
      - name: yahoo
        image: docker.io/mungu42/yahoo
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
###############################################
# Google service
###############################################
# apiVersion: v1
# kind: Service
# metadata:
#   name: ratings
#   labels:
#     app: ratings
#     service: ratings
# spec:
#   ports:
#   - port: 8080
#     name: http
#   selector:
#     app: ratings
# ---
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: bookinfo-ratings
#   labels:
#     account: ratings
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: ratings-v1
#   labels:
#     app: ratings
#     version: v1
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: ratings
#       version: v1
#   template:
#     metadata:
#       labels:
#         app: ratings
#         version: v1
#     spec:
#       serviceAccountName: bookinfo-ratings
#       containers:
#       - name: ratings
#         image: docker.io/mungu42/yahoo
#         imagePullPolicy: IfNotPresent
#         ports:
#         - containerPort: 8080
